# Generated by Django 4.0.2 on 2022-04-02 22:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pacient', '0002_alter_pacient_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pacient',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pacient', to=settings.AUTH_USER_MODEL),
        ),
    ]
