# Generated by Django 4.0.4 on 2022-04-21 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0004_pacient_max_glucose_level_pacient_min_glucose_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacient',
            name='carb_counting',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pacient',
            name='isf',
            field=models.IntegerField(null=True, verbose_name='Insulin Sensitivity Factor'),
        ),
    ]
