# Generated by Django 4.0.2 on 2022-03-19 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pacient', '0001_initial'),
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurement',
            name='pacient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='pacient.pacient'),
        ),
    ]
