# Generated by Django 4.0.2 on 2022-03-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurement',
            name='glicemy',
            field=models.IntegerField(default=0),
        ),
    ]
