# Generated by Django 4.0.4 on 2022-04-21 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_rename_glicemy_measurement_glycemia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='measurement',
            options={'ordering': ['timestamp']},
        ),
        migrations.AddField(
            model_name='measurement',
            name='measurement_type',
            field=models.CharField(choices=[('POS CAFE', 'Pós café'), ('POS_ALMOCO', 'Pós almoço'), ('POST_LANCHE', 'Pós lanche'), ('POST_JANTAR', 'Pós jantar'), ('MADRUGADA', 'Madrugada'), ('OUTRO', 'Outro')], default='OUTRO', max_length=200),
        ),
        migrations.AddField(
            model_name='measurement',
            name='obs',
            field=models.TextField(null=True, verbose_name='Measurement description'),
        ),
        migrations.AddField(
            model_name='measurement',
            name='ui_correction',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
