# Generated by Django 4.0.4 on 2022-04-21 20:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('injection', '0002_alter_injection_ui'),
        ('measurement', '0004_alter_measurement_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurement',
            name='ui_correction',
        ),
        migrations.AddField(
            model_name='measurement',
            name='injection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='injection.injection'),
        ),
    ]
