# Generated by Django 4.0.2 on 2022-03-23 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Insulin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('RAPID_ACTING', 'Rapid Acting'), ('SHORT_ACTING', 'Short Acting'), ('INTERMEDIATE_ACTING', 'Intermediate Acting'), ('LONG_ACTING', 'Long Acting'), ('ULTRA_LONG_ACTING', 'Ultra Long Acting'), ('INHALED', 'Inhaled')], max_length=50)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
