# Generated by Django 4.0.4 on 2022-04-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insulin', '0002_insulin_dosis_insulin_pacient'),
    ]

    operations = [
        migrations.AddField(
            model_name='insulin',
            name='is_correction',
            field=models.BooleanField(default=False),
        ),
    ]
