# Generated by Django 4.0.2 on 2022-04-03 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('BREAKFAST', 'Café da manhã'), ('LUNCH', 'Almoço'), ('SNACK', 'Lanche'), ('DINNER', 'Jantar')], max_length=32, null=True),
        ),
    ]
