# Generated by Django 4.0.4 on 2022-04-19 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal', '0003_alter_meal_cho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='type',
            field=models.CharField(choices=[('CAFE_DA_MANHA', 'Café da manhã'), ('ALMOCO', 'Almoço'), ('LANCHE', 'Lanche'), ('JANTAR', 'Jantar')], max_length=32, null=True),
        ),
    ]
